### ISSUE TITLE
Feature request of nonuniform scaling of broken regions and issue on mouse hover to plot

### ISSUE THREAD

**Issue by sahaskn** [bendichter/brokenaxes#24]
@developers, First thank you for this very handy tool which I just came to know yesterday.

One issue I found is on hovering mouse at different broken region on the plot, the x, y co-ordinates on line plot, does not provide the right values on the status bar of matplotlib figure.

Feature request:
 If it is possible, to have different scaling rather than 1:1 for the broken regions.

**Comment by bendichter** [comment]
Thanks for the kind words, @sahaskn.

The real point of this library is to have the extent of the broken regions be proportional to the range of the data of that region. If you want to have a different spacing, you are better off using `GridSpec` and creating it yourself.

Could you provide a screenshot of what you mean with the coordinates issue?

**Comment by sahaskn** [comment]
![image](https://user-images.githubusercontent.com/26824040/55649444-96f0da80-57a8-11e9-8718-88459d21a548.png)

Sure here you go. The mouse pointer is not visible here due to screenshot but it is close to 0.5 tick.

**Comment by weber-s** [comment]
Hello!
First, many thanks for this work.
That funny, I just needed to plot a broken axis with 2 different scales yesterday... So I looked in the code and in fact, it's pretty easy to adapt it to this will!

Here you can find it. Since it is not the purpose of this lib, I let @bendichter decide if this patch should be merged or not...

https://github.com/weber-s/brokenaxes/tree/add_fixed_width_and_height_ratio
(and the commit: https://github.com/weber-s/brokenaxes/commit/3688b9a1fd215f0832b4cf269426851b826978a2)

The idea is to bypass the "height_ratios" and "width_ratios" computation if the user specify it.

Here is an example:

```py
import numpy as np
from brokenaxes import brokenaxes

x = np.linspace(0,5,100)
sin = np.sin(x)
cos = np.cos(x)

bax = brokenaxes(ylims=((-1, -0.5), (0.5, 1)), height_ratios=[1, 3])

bax.plot(x, sin, x, cos)
```
![Figure_1](https://user-images.githubusercontent.com/25247745/55963929-f735bf80-5c73-11e9-9974-9e0798bfab37.png)

**Comment by sahaskn** [comment]
@weber-s : Thanks a lot! A document with different scale and different step will be very helpful.

**Comment by weber-s** [comment]
@sahaskn You're welcome :) Here are the docs: https://github.com/bendichter/brokenaxes/pull/29
